[server]
headless = true
port = 8502
enableCORS = true
enableXsrfProtection = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 8502

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0f0f23"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#ffffff" 