# AI Contact Scraper Pro - Example Secrets Configuration
# Copy this file to 'secrets.toml' and replace placeholder values with your actual API keys
# NEVER commit your actual secrets.toml file to version control!

# Core API Keys (Required for full functionality)
RAPIDAPI_KEY = "your_rapidapi_key_here"  # Get from: https://rapidapi.com/
APIFY_KEY = "apify_api_your_key_here"     # Get from: https://console.apify.com/account/integrations
SCRAPE_GRAPH_API_KEY = "sgai-your-scrape-graph-key-here"  # Optional

# OpenAI Configuration (Required for AI extraction)
OPENAI_API_KEY = "your_openai_api_key_here"  # Get from: https://platform.openai.com/api-keys
OPENAI_MODEL = "gpt-4o-2024-11-20"

# Google Services (Optional)
GOOGLE_API_KEY = "your_google_api_key_here"  # Get from: https://console.cloud.google.com/

# Database (Supabase) - For user authentication and data storage
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_KEY = "your_supabase_service_role_key_here"

# AI Services (Required for various features)
XAI_API_KEY = "xai-your-xai-api-key-here"        # Optional
SERPER_API_KEY = "your_serper_api_key_here"      # Get from: https://serper.dev/
OPENROUTER_API_KEY = "your_openrouter_key_here"  # Get from: https://openrouter.ai/

# Email Configuration (Optional - for notifications)
EMAIL_SENDER_ADDRESS = "your_email@gmail.com"
EMAIL_SENDER_PASSWORD = "your_app_password_here"  # Use Gmail app password
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

# JWT Authentication (Required for user system)
JWT_SECRET_KEY = "your_secure_jwt_secret_key_here"  # Generate a secure random string
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

# Twitter API Configuration (Optional - only if using Twitter features)
TWITTER_API_KEY = "your_twitter_api_key"
TWITTER_API_SECRET = "your_twitter_api_secret"
TWITTER_BEARER_TOKEN = "your_twitter_bearer_token"
TWITTER_ACCESS_TOKEN = "your_twitter_access_token"
TWITTER_ACCESS_TOKEN_SECRET = "your_twitter_access_token_secret"

# Twitter OAuth (Optional)
CLIENT_ID = "your_twitter_client_id"
CLIENT_SECRET = "your_twitter_client_secret"
CALLBACK_URL = "http://127.0.0.1:8000/twitter/connect/" 